---
title: "Chicago Diagnostic from 2012-2016 5-Year ACS"
author: "Jun Wong"
date: "1/11/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidycensus)
library(sf)
library(RColorBrewer)
options(tigris_use_cache = TRUE)
```


```{r pressure, echo=FALSE, warning=FALSE, include=FALSE}

# Data Prep
chicago_msa <- get_acs(geography = "tract", 
              variables = c(medincome = "B19013_001", population_unw = "B00001_001", 
                            housing = "B00002_001", poverty_total = "B05010_001",
                            below_poverty_level = "B05010_002", 
                            total_pop = "B02001_001",
                            black_pop = "B02001_003" 
                            ), 
              state = c("IL", "IN"), 
              counties = c("Cook", "DuPage", "Kane", "Lake", 
                           "McHenry", "Will", "DeKalb", "Grundy", 
                           "Kankakee", "Kendall"),
              year = 2016) %>%
  pivot_wider(id_cols = "GEOID",
              names_from="variable",
              values_from="estimate")

# Get the geometry
chicago_shp <- st_read("Data/Boundaries - Census Tracts - 2010", 
                       "geo_export_17682e57-ce98-43d5-9369-ca3878b38a63") %>% 
  rename(GEOID = geoid10)

# Create centroids
# chicago_centroid <- st_centroid(chicago_shp) %>% 
#   st_coordinates() %>% 
#   cbind(chicago_shp) %>% 
#   st_drop_geometry()
# write.csv(chicago_centroid, "Data/chicago_tract_centroids.csv")

chicago_msa <- left_join(chicago_shp, chicago_msa, by="GEOID") %>% 
  st_as_sf()

```

# Population

```{r}

ggplot(chicago_msa) + 
  geom_sf(aes(fill=population_unw), color="grey70", lwd=0.1) + 
  scale_fill_distiller(palette = "YlOrBr", na.value = "grey50", 
                       direction=1, name = "Population") + 
  theme_void() +
  theme(legend.position = "bottom", legend.box="horizontal",
        legend.key.width = unit(1.5, "cm")) + 
  guides(fill = guide_colorbar(title.position="top", 
                                     title.hjust =0.5))

```

- What is happening in that one census tract? 

# Number of Housing Units per Capita 

```{r}
chicago_msa <- chicago_msa %>% 
  mutate(housing_per_capita = housing / population_unw)

ggplot(chicago_msa) + 
  geom_sf(aes(fill=housing_per_capita), color="grey70", lwd=0.1) + 
  scale_fill_distiller(palette = "YlOrBr", na.value = "grey50", 
                       direction=1, name = "Housing per Capita") + 
  theme_void() +
  theme(legend.position = "bottom", legend.box="horizontal",
        legend.key.width = unit(1.5, "cm")) + 
  guides(fill = guide_colorbar(title.position="top", 
                                     title.hjust =0.5))
```

- The weird tract from above is not that large but somehow it has very low housing per capita 

# Percent Black Population

```{r}

chicago_msa <- chicago_msa %>% 
  mutate(percent_black_pop = black_pop / total_pop)

ggplot(chicago_msa) + 
  geom_sf(aes(fill=percent_black_pop), color="grey70", lwd=0.1) + 
  scale_fill_distiller(palette = "YlOrBr", na.value = "grey50", 
                       direction=1, name = "Share Black Population") + 
  theme_void() +
  theme(legend.position = "bottom", legend.box="horizontal",
        legend.key.width = unit(1.5, "cm")) + 
  guides(fill = guide_colorbar(title.position="top", 
                                     title.hjust =0.5))

```

# Median Income

```{r}

ggplot(chicago_msa) + 
  geom_sf(aes(fill=medincome), color="grey70", lwd=0.1) + 
  scale_fill_distiller(palette = "YlOrBr", na.value = "grey50", 
                       direction=1, name = "Median Income") + 
  theme_void() +
  theme(legend.position = "bottom", legend.box="horizontal",
        legend.key.width = unit(1.5, "cm")) + 
  guides(fill = guide_colorbar(title.position="top", 
                                     title.hjust =0.5))

```

# Percent below poverty level 

```{r}

chicago_msa <- chicago_msa %>% 
  mutate(percent_below_poverty_level = below_poverty_level / poverty_total)

ggplot(chicago_msa) + 
  geom_sf(aes(fill=percent_below_poverty_level), color="grey70", lwd=0.1) + 
  scale_fill_distiller(palette = "YlOrBr", na.value = "grey50", 
                       direction=1, 
                       name = "Share Population Below Poverty Level") + 
  theme_void() + 
  theme(legend.position = "bottom", legend.box="horizontal",
        legend.key.width = unit(1.5, "cm")) + 
  guides(fill = guide_colorbar(title.position="top", 
                                     title.hjust =0.5))

```

